### ISSUE TITLE
Error on npm run production

### ISSUE THREAD

**Issue by lucaros97** [arkokoley/pdfvuer#38]
When running `npm run production` on a Laravel + Vue application it doesn't work and throw this error:
```
> @ production C:\wamp64\www\JUICE\projects\projectName
> cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

CssSyntaxError: C:\css\app.css:54383:3: Unknown word
    at Input.error (C:\wamp64\www\JUICE\projects\projectName\node_modules\postcss\lib\input.js:130:16)
    at Parser.unknownWord (C:\wamp64\www\JUICE\projects\projectName\node_modules\postcss\lib\parser.js:563:22)
    at Parser.decl (C:\wamp64\www\JUICE\projects\projectName\node_modules\postcss\lib\parser.js:235:16)
    at Parser.other (C:\wamp64\www\JUICE\projects\projectName\node_modules\postcss\lib\parser.js:166:12)
    at Parser.parse (C:\wamp64\www\JUICE\projects\projectName\node_modules\postcss\lib\parser.js:77:16)
    at parse (C:\wamp64\www\JUICE\projects\projectName\node_modules\postcss\lib\parse.js:17:12)
    at new LazyResult (C:\wamp64\www\JUICE\projects\projectName\node_modules\postcss\lib\lazy-result.js:60:16)
    at Processor.<anonymous> (C:\wamp64\www\JUICE\projects\projectName\node_modules\postcss\lib\processor.js:138:12)
    at Processor.process (C:\wamp64\www\JUICE\projects\projectName\node_modules\postcss\lib\processor.js:117:23)
    at Function.creator.process (C:\wamp64\www\JUICE\projects\projectName\node_modules\postcss\lib\postcss.js:148:43)
    at OptimizeCssAssetsWebpackPlugin.processCss (C:\wamp64\www\JUICE\projects\projectName\node_modules\optimize-css-assets-webpack-plugin\src\index.js:73:21)
    at Object.processor (C:\wamp64\www\JUICE\projects\projectName\node_modules\optimize-css-assets-webpack-plugin\src\index.js:13:18)
    at each (C:\wamp64\www\JUICE\projects\projectName\node_modules\last-call-webpack-plugin\src\index.js:150:10)
    at arrayEach (C:\wamp64\www\JUICE\projects\projectName\node_modules\lodash\_arrayEach.js:15:9)
    at forEach (C:\wamp64\www\JUICE\projects\projectName\node_modules\lodash\forEach.js:38:10)
    at OptimizeCssAssetsWebpackPlugin.process (C:\wamp64\www\JUICE\projects\projectName\node_modules\last-call-webpack-plugin\src\index.js:147:5)
    at compilation.hooks.optimizeChunkAssets.tapPromise.chunks (C:\wamp64\www\JUICE\projects\projectName\node_modules\last-call-webpack-plugin\src\index.js:178:28)
    at _next0 (eval at create (C:\wamp64\www\JUICE\projects\projectName\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:9:17)
    at _err0 (eval at create (C:\wamp64\www\JUICE\projects\projectName\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:25:1)
    at taskRunner.run (C:\wamp64\www\JUICE\projects\projectName\node_modules\terser-webpack-plugin\dist\index.js:321:9)
    at step (C:\wamp64\www\JUICE\projects\projectName\node_modules\terser-webpack-plugin\dist\TaskRunner.js:87:9)
    at done (C:\wamp64\www\JUICE\projects\projectName\node_modules\terser-webpack-plugin\dist\TaskRunner.js:98:30)
    at tryCatcher (C:\wamp64\www\JUICE\projects\projectName\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\wamp64\www\JUICE\projects\projectName\node_modules\bluebird\js\release\promise.js:517:31)
    at Promise._settlePromise (C:\wamp64\www\JUICE\projects\projectName\node_modules\bluebird\js\release\promise.js:574:18)
    at Promise._settlePromise0 (C:\wamp64\www\JUICE\projects\projectName\node_modules\bluebird\js\release\promise.js:619:10)
    at Promise._settlePromises (C:\wamp64\www\JUICE\projects\projectName\node_modules\bluebird\js\release\promise.js:699:18)
    at Promise._fulfill (C:\wamp64\www\JUICE\projects\projectName\node_modules\bluebird\js\release\promise.js:643:18)
    at Promise._resolveCallback (C:\wamp64\www\JUICE\projects\projectName\node_modules\bluebird\js\release\promise.js:437:57)
    at Promise._settlePromiseFromHandler (C:\wamp64\www\JUICE\projects\projectName\node_modules\bluebird\js\release\promise.js:529:17)
    at Promise._settlePromise (C:\wamp64\www\JUICE\projects\projectName\node_modules\bluebird\js\release\promise.js:574:18)
    at Promise._settlePromise0 (C:\wamp64\www\JUICE\projects\projectName\node_modules\bluebird\js\release\promise.js:619:10)
    at Promise._settlePromises (C:\wamp64\www\JUICE\projects\projectName\node_modules\bluebird\js\release\promise.js:699:18)
    at Promise._fulfill (C:\wamp64\www\JUICE\projects\projectName\node_modules\bluebird\js\release\promise.js:643:18)
    at Promise._resolveCallback (C:\wamp64\www\JUICE\projects\projectName\node_modules\bluebird\js\release\promise.js:437:57)
    at Promise._settlePromiseFromHandler (C:\wamp64\www\JUICE\projects\projectName\node_modules\bluebird\js\release\promise.js:529:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ production: `cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ production script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Luca Rossi\AppData\Roaming\npm-cache\_logs\2019-11-12T15_48_27_673Z-debug.log
```

Any solution?

**Comment by lucaros97** [comment]
Founded the problem. Dynamic imports aren't supported in Mix 4. So if I import pdfvuer in a component it throw the error.
The problem now is that if I put:
```
import pdfvuer from 'pdfvuer'
Vue.use(pdfvuer)
```

In the page i will see this error:
`Uncaught (in promise) ReferenceError: pdfvuer is not defined`

**Comment by arkokoley** [comment]
I overhauled the entire codebase.. and now distribute esm and commonjs files. Please upgrade to v1. 7.1 to see if that fixes your issue.
