### ISSUE TITLE
Module build failed: ReferenceError: Unknown plugin "@babel/transform-runtime"

### ISSUE THREAD

**Issue by t0n1zz** [arkokoley/pdfvuer#55]
i got this error

```
ERROR in ./node_modules/babel-loader/lib?{"cacheDirectory":true,"presets":[["env",{"modules":false,"targets":{"browsers":["> 2%"],"uglify":true}}]],"plugins":["transform-object-rest-spread",["transform-runtime",{"polyfill":false,"helpers":false}]]}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./node_modules/pdfvuer/src/Pdfvuer.vue
Module build failed: ReferenceError: Unknown plugin "@babel/transform-runtime" specified in "/Users/tony/Sites/bkcuvue/node_modules/pdfvuer/.babelrc" at 0, attempted to resolve relative to "/Users/tony/Sites/bkcuvue/node_modules/pdfvuer"
    at /Users/tony/Sites/bkcuvue/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/Users/tony/Sites/bkcuvue/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/tony/Sites/bkcuvue/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/Users/tony/Sites/bkcuvue/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/tony/Sites/bkcuvue/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/tony/Sites/bkcuvue/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/tony/Sites/bkcuvue/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/tony/Sites/bkcuvue/node_modules/babel-loader/lib/index.js:50:20)
    at /Users/tony/Sites/bkcuvue/node_modules/babel-loader/lib/fs-cache.js:118:18
    at ReadFileContext.callback (/Users/tony/Sites/bkcuvue/node_modules/babel-loader/lib/fs-cache.js:31:21)
    at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:245:13)
 @ ./node_modules/pdfvuer/src/Pdfvuer.vue 4:21-344
 @ ./node_modules/babel-loader/lib?{"cacheDirectory":true,"presets":[["env",{"modules":false,"targets":{"browsers":["> 2%"],"uglify":true}}]],"plugins":["transform-object-rest-spread",["transform-runtime",{"polyfill":false,"helpers":false}]]}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./resources/assets/js/views/pertemuanBKCU/detail.vue
 @ ./resources/assets/js/views/pertemuanBKCU/detail.vue
 @ ./resources/assets/js/routes.js
 @ ./resources/assets/js/app.js
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss
```

**Comment by AtillaPehlivan** [comment]
hi , i got same issue 
for now , you can set the previous version ` "pdfvuer": "1.4.0",` in _package.json_

**Comment by t0n1zz** [comment]
just set it to 1.4.0 and still getting same error

**Comment by Alberghini** [comment]
You need to run 

> npm install

 again

Worked for me!

**Comment by arkokoley** [comment]
I overhauled the entire codebase.. and now distribute esm and commonjs files. Please upgrade to v1. 7.1 to see if that fixes your issue.
